import datetime
year1=int(input('type a year: '))
month1=int(input("type a month: "))
day1=int(input("type a day: "))
hour1=int(input("type a hour: "))
minute1=int(input("type a minute: "))
second1=int(input("type a second: "))
x=datetime.datetime(year1, month1, day1,hour1,minute1, second1)
year2=int(input('type a year: '))
month2=int(input("type a month: "))
day2=int(input("type a day: "))
hour2=int(input("type a hour: "))
minute2=int(input("type a minute: "))
second2=int(input("type a second: "))
y=datetime.datetime(year2, month2, day2,hour2,minute2, second2)
diff_days=x-y
diff_sec=diff_days.total_seconds()

print(diff_days)
print(diff_sec, " seconds")